# Generated by Django 6.1.1 on 2026-09-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('fullstack', 'Full Stack Development'), ('other', 'Other')], max_length=20),
        ),
    ]
