# Generated by Django 6.1.1 on 2026-09-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(default='2026-12-31'),
            preserve_default=False,
        ),
    ]
